Allow nullable types in Flow's firstOrNull extension
Kotlin/kotlinx.coroutines pull request #2230
Opened 2020-09-04 18:21 UTC by ansman

This closes #2229

2020-09-24 11:24 UTC, qwwdfsad reviewed
Thanks!

Could you please also remove `Any` upper bound from `singleOrNull` operator and add a corresponding unit test?

2020-09-24 16:20 UTC, ansman commented
Done

2020-09-24 16:21 UTC, ansman commented on kotlinx-coroutines-core/common/src/flow/terminal/Reduce.kt
>   * Returns `null` if the flow did not contain an element matching the [predicate].
Do we want to comment on what happens if the flow contains a single `null` value or let that be implied?

2020-10-05 17:13 UTC, qwwdfsad requested changes
`assertFailsWith<NoSuchElementException> { flowOf<Int?>().singleOrNull() }` doesn't actually fail but returns `null` instead. Added test doesn't pass

2020-10-05 17:17 UTC, ansman commented
My bad. I'm unable to run the tests locally because java 6 is needed.

2020-10-06 08:17 UTC, LouisCAD commented
@ansman Read the updated `CONTRIBUTING.md` on the main/master branch, it's specified you can make the env variable point to a newer JDK, including JDK11+

2020-10-07 11:29 UTC, qwwdfsad approved these changes
Multiple `null` values are handled incorrectly.
I've created #2287 with your changes and fixed it in https://github.com/Kotlin/kotlinx.coroutines/pull/2287/commits/7d006bbf028e3575469f35ddc50411afc4bb122e to reduce a rountrip time and merge it.

Thanks for raising the issue and your contribution, it's always great to evolve our API based on our users feedback!

2020-10-07 11:29 UTC, closed without merging