Add getCurrentJob and getCurrentScopeJob functions
Kotlin/kotlinx.coroutines pull request #2245
Opened 2020-09-12 06:59 UTC by recheej

Resolves #2159 .

Adding different names for the suspend and `CoroutineScope` extension versions since there can be some confusion. Added docs and did api dump

2020-09-21 08:50 UTC, elizarov commented
@recheej Can you, please, elaborate what's your use-case for these functions? What kind of code needs them?

2020-09-21 14:49 UTC, recheej commented
@elizarov I personally would use these functions for debugging coroutines code (see state of job, children, etc). But I could also see them being used for lower level coroutines work or for logging state of things.

In the end, I think the `Job` is such an important context element that it deserves its own function(s).

2020-09-24 10:04 UTC, qwwdfsad requested changes
Thanks to your contribution!
We've discussed it internally and decided that it's not the addition we are ready to make. It's unclear who and how is going to use it, its naming is misaligned with existing memebrs (e.g. `CoroutineScope.coroutineContext`, but `currentCoroutineContext()`).

We'd like to introduce the only `coroutineContext.job: Job?` extension property for the sake of brevity where it is necessary. If you want to do this extra-mile and replace your PR with that, we'd be happy to help you with review and integration. If not, it's completely okay to tell us, then we are going to implement it ourselves

2020-09-24 15:07 UTC, recheej commented
Sure I can do that change

2020-10-17 03:22 UTC, closed without merging