Fix BlockHound false positives
Kotlin/kotlinx.coroutines pull request #2331
Opened 2020-10-23 12:48 UTC by dkhalanskyjb

2020-10-23 14:26 UTC, qwwdfsad requested changes
Please revisit a few more places on our code that rely on fast locking:
- `StateFlow` and `SharedFlow`
- `JobSupport` (`finalizeFinishingState` & co.)

2020-10-23 14:26 UTC, qwwdfsad commented on kotlinx-coroutines-debug/src/CoroutinesBlockHoundIntegration.kt
> +        // These classes use a lock internally, but should be safe to use.
I would rather write something a bit more encouraging for external users such as "These classes use a lock internally, but only for well-known, short and isolated state transitions that are known to be short and fast"

2020-10-23 14:26 UTC, qwwdfsad commented on kotlinx-coroutines-debug/src/CoroutinesBlockHoundIntegration.kt
> +        for (method in listOf(
Currently, it's a bit hard to read and get through. Could you please split it to a few methods?
Like
```
allowBlockingCallsInsideChannelImpl()
allowBlockingCallsInsideReflection()
... etc. ...
```

2020-10-23 16:41 UTC, dkhalanskyjb commented
Yeah, I completely missed that some code is protected using `synchronized`.

2020-10-26 07:12 UTC, qwwdfsad approved these changes
Otherwise looks good, great job

2020-10-26 07:12 UTC, qwwdfsad commented on kotlinx-coroutines-debug/src/CoroutinesBlockHoundIntegration.kt
> +    /** Allows blocking when enqueuing tasks into a thread pool.
In our codestyle, we typically start comment on the next line after `/**`

2020-10-26 08:40 UTC, merged