Add JVM IR target in build_snapshot_train mode
Kotlin/kotlinx.coroutines pull request #2358
Opened 2020-11-02 10:01 UTC by ALikhachev

2020-11-03 11:26 UTC, udalov commented
As in https://github.com/ktorio/ktor/pull/2175#issuecomment-721058147, I suggest not to commit API dumps for JVM IR, but rather mute the tests if possible (with the option to unmute locally).

2020-11-13 14:12 UTC, qwwdfsad requested changes
I've skimmed through PR and have the following comments that should be applied to all PRs in libraries:

1) I see a lot of irrelevant changes in gradle configurations. Either they should be avoided (-> reverted or amended), or a comment explaining why this change was done is needed. Now it's far from being clear, neither from the change nor from commit messages.

2) Api dumps should not be touched. They should be left as-is for JVM and be ignored for JVM IR

3) Subtle places (e.g.: `attributesSchema`, `jvm-multiplatform` etc.) should be added with a comment

3) Can we avoid migration to MPP plugin in JVM-only project? This change is not really desirable

2020-11-13 14:12 UTC, qwwdfsad commented on build.gradle
> +    kotlin {
Why this change is require?

2020-11-13 15:15 UTC, ALikhachev commented
During private discussion we've decided to try another way. I'll open new PR.

2020-11-13 15:15 UTC, closed without merging