Update SharedFlow documentation
Kotlin/kotlinx.coroutines pull request #2437
Opened 2020-12-07 15:27 UTC by qwwdfsad

2020-12-07 16:34 UTC, ivakub commented
https://youtrack.jetbrains.com/issue/KT-43770

2020-12-09 15:21 UTC, elizarov requested changes

2020-12-09 15:21 UTC, elizarov commented on kotlinx-coroutines-core/common/src/flow/SharedFlow.kt
> +     * Emits a [value] to this shared flow, suspending on buffer overflow until all subscribers receive the value
That's a correct statement only about a shared flow without a buffer. A buffered flow only suspends when there's no room in the buffer. So, without a buffer it translates into suspension until every subscribers receives (because there's no buffer to store it).

2021-03-01 16:15 UTC, qwwdfsad commented on kotlinx-coroutines-core/common/src/flow/SharedFlow.kt
> +     * Emits a [value] to this shared flow, suspending on buffer overflow until all subscribers receive the value
Reverted this line

2021-03-02 16:42 UTC, elizarov approved these changes
Nice.

2021-03-24 08:02 UTC, merged