Clarify docs about restriction on MutableSharedFlow function's onBufferOverflow parameter.
Kotlin/kotlinx.coroutines pull request #2501
Opened 2021-01-27 17:26 UTC by zach-klippenstein

The existing docs are confusing to me – it's not clear that "supported" in this case means "passing a value other than the default is supported". I've also included an explanation as to why this restriction makes sense.

2021-01-29 14:20 UTC, elizarov requested changes

2021-01-29 14:20 UTC, elizarov commented on kotlinx-coroutines-core/common/src/flow/SharedFlow.kt
> + *   flow has no buffer, then [emit][MutableSharedFlow.emit] will always suspend unless there is at least one subscriber ready to accept the
> when the flow has no buffer, then emit will always suspend **unless** there is at least one subscriber ready to accept the

This should be "will suspend **if** there is at least one subscriber". If there are no subscribes, then emit never suspends. It just drops the emitted value.

2021-01-29 19:44 UTC, zach-klippenstein commented on kotlinx-coroutines-core/common/src/flow/SharedFlow.kt
> + *   flow has no buffer, then [emit][MutableSharedFlow.emit] will always suspend unless there is at least one subscriber ready to accept the
How are these?
1. "then [emit][MutableSharedFlow.emit] will always suspend when there is at least one subscriber and at least one subscriber is not ready to accept the new value. It will never suspend when there are no subscribers."
1. "then [emit][MutableSharedFlow.emit] will always suspend when any subscriber is not ready to accept the new value. It will never suspend when there are no subscribers."
1. "then [emit][MutableSharedFlow.emit] will always suspend when any subscriber is exerting backpressure. It will never suspend when there are no subscribers."

2021-02-25 18:50 UTC, zach-klippenstein commented on kotlinx-coroutines-core/common/src/flow/SharedFlow.kt
> + *   flow has no buffer, then [emit][MutableSharedFlow.emit] will always suspend unless there is at least one subscriber ready to accept the
@elizarov Let me know what you think of the above wordings and I'll update the PR.

2021-03-02 16:41 UTC, elizarov commented
It turned to be a challenge to rephrase. I've added my own clarifications on top of yours in #2560. Closing this PR.

2021-03-02 16:41 UTC, closed without merging