Add atomic update extension functions to MutableStateFlow
Kotlin/kotlinx.coroutines pull request #2721
Opened 2021-05-20 22:13 UTC by lowasser

Addresses https://github.com/Kotlin/kotlinx.coroutines/issues/2720.

2021-05-21 12:28 UTC, qwwdfsad requested changes
Good job! Please don't forget to run `./gradlew apiDump` as well

2021-05-21 12:28 UTC, qwwdfsad commented on kotlinx-coroutines-core/common/test/flow/sharing/StateFlowTest.kt
> +    fun update() = runTest {
```suggestion
    fun testUpdate() = runTest {
```

2021-05-21 12:28 UTC, qwwdfsad commented on kotlinx-coroutines-core/common/src/flow/StateFlow.kt
> +public inline fun <T> MutableStateFlow<T>.updateAndGet(function: (T) -> T): T {
This function seems to be copy-pasted and thus the code does not compile. Have you meant `getAndUpdate` instead?

2021-05-21 18:39 UTC, lowasser commented
Done!

2021-05-25 12:06 UTC, qwwdfsad commented
Merged manually as part of #2729, thanks!

I rewrote the tests (they were single-threaded as opposed to their name and also failed on JS) and changed the base branch to `develop`. We have a comprehensive contribution guide here that cover such common pitfalls: https://github.com/Kotlin/kotlinx.coroutines/blob/master/CONTRIBUTING.md#submitting-prs

2021-05-25 12:06 UTC, closed without merging