Update channels.md add a missing playground
Kotlin/kotlinx.coroutines pull request #3258
Opened 2022-04-19 02:09 UTC by liuchong

Just update doc, make code could click and run on [play.kotlinlang.org](https://play.kotlinlang.org)

2022-04-22 07:49 UTC, dkhalanskyjb requested changes

2022-04-22 07:49 UTC, dkhalanskyjb commented on docs/topics/coroutines-basics.md
>  example will exhaust the playground's heap memory; don't make it runnable. -->
This is relevant.

2022-04-23 00:01 UTC, liuchong commented on docs/topics/coroutines-basics.md
>  example will exhaust the playground's heap memory; don't make it runnable. -->
Thanks, changed 👀

2022-05-17 12:44 UTC, merged

2022-05-17 12:44 UTC, dkhalanskyjb commented
Thanks!