Preparation for atomicfu JVM IR plugin application in 1.7.20
Kotlin/kotlinx.coroutines pull request #3455
Opened 2022-09-19 10:49 UTC by mvicsokolova

- Integration test: excluded Metadata annotation while checking bytecode of class files (`testNoAtomicfuInMppJar`)

Used this solution instead of adding post transformation of metadata by `AtomicfuGradlePlugin`, because the problem is on the side of the compiler plugin: it transforms the backing field of the property, though the property itself remains in the metadata. So, when I'll fix that in the compiler plugin, there will be no atomicfu references left in the metadata.

- Moved `SegmentBasedQueue` class that used inline atomic extension (`findSegmentAndMoveForward`) to the main module.

[Here](https://buildserver.labs.intellij.net/buildConfiguration/Kotlin_BuildPlayground_MilkyWayMargaritaBobova_kotlinxtraincoroutines/216507717?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true) is the test coroutines build, including the Integration Test step

2022-09-19 15:52 UTC, qwwdfsad requested changes

2022-09-19 15:52 UTC, qwwdfsad commented on integration-testing/src/mavenTest/kotlin/MavenPublicationAtomicfuValidator.kt
> +            // check the bytecode of the class for ATOMIC_FU_REF excluding metadata
Please drop a comment about when we can remove this workaround and why it is needed in the first place

2022-09-19 15:52 UTC, qwwdfsad commented on kotlinx-coroutines-core/jvm/test/internal/SegmentListTest.kt
> -package kotlinx.coroutines.internal
I think we can remove it as it's the only way for now.

Whether we need another test or not can be checked by eye-balling the result of Kover: `./gradlew :kotlinx-coroutines-core:koverReport -Pkover.enabled=true`

2022-09-20 11:28 UTC, mvicsokolova commented on kotlinx-coroutines-core/jvm/test/internal/SegmentListTest.kt
> -package kotlinx.coroutines.internal
Seems ok, all methods in `ConcurrentLinkedListKt` are covered

2022-09-20 13:49 UTC, qwwdfsad approved these changes
👍

2022-09-20 15:32 UTC, merged