@OptIn for experimental identityHashCode
Kotlin/kotlinx.coroutines pull request #3693
Opened 2023-03-28 13:49 UTC by qurbonzoda

The function was made experimental as a part of efforts to stabilize Native stdlib.

2023-03-28 13:55 UTC, qwwdfsad approved these changes

2023-03-28 13:57 UTC, qwwdfsad requested changes
Please rebase your changes on top of `develop` -- all PRs should go through development branch first

2023-03-28 14:02 UTC, qurbonzoda commented
Rebased onto `develop`.

2023-03-29 14:14 UTC, qwwdfsad approved these changes

2023-03-29 16:34 UTC, merged