Fix newSingleThreadContext awaiting cancelled scheduled coroutines
Kotlin/kotlinx.coroutines pull request #3769
Opened 2023-06-01 13:06 UTC by dkhalanskyjb

Before the change, the Worker is not notified about its work being cancelled, due to no API being present for that.
We work around the issue by checking every 100 milliseconds whether cancellation happened.

Fixes #3768

2023-06-01 13:13 UTC, dkhalanskyjb commented
Ah, ok, I get it, it's because this dispatcher is reused for the `DefaultExecutor`.

2023-06-01 13:19 UTC, dkhalanskyjb commented
Maybe it makes sense to have `WorkerDispatcher` be only for the `DefaultExecutor` and have `newSingleThreadContext` be `newFixedThreadPoolContext(1)`, like on the JVM.

2023-06-01 16:21 UTC, qwwdfsad approved these changes
Nice one!

I'm onboard with making `WorkerDispatcher` available only for `DefaultExecutor`

2023-06-01 16:21 UTC, qwwdfsad commented on kotlinx-coroutines-core/native/src/MultithreadedDispatchers.kt
> +            val durationUntilTarget = -targetMoment.elapsedNow()
Was a bit confused at the beginning when looking at documentation only, have filed https://youtrack.jetbrains.com/issue/KT-59044/Improve-various-aspects-of-TimeSource-documentation

2023-06-01 16:21 UTC, qwwdfsad commented on kotlinx-coroutines-core/native/src/MultithreadedDispatchers.kt
> +            val durationUntilTarget = -targetMoment.elapsedNow()
Probably we can ignore "infinity" problem for now -- such check would be untestable anyway

2023-06-28 10:47 UTC, qwwdfsad commented on kotlinx-coroutines-core/native/src/MultithreadedDispatchers.kt
> +        val targetMoment = TimeSource.Monotonic.markNow() + timeMillis.milliseconds
Still unused

2023-06-28 10:49 UTC, qwwdfsad requested changes
Our build started flaking consistently after the change, could you please take a look?
Otherwise LGTM

2023-06-28 10:58 UTC, dkhalanskyjb commented
The first build failure was on me, an API dump changed, which I later fixed, but the second one seems to be just Windows doing its thing, no?

2023-06-28 10:59 UTC, dkhalanskyjb commented
Ah, no, I see now that something's off.

2023-06-28 11:08 UTC, dkhalanskyjb commented
Who knew? This was an actual bug. Turns out `executeAfter` doesn't crashes on negative numbers.

2023-06-28 15:56 UTC, qwwdfsad approved these changes

2023-06-29 09:21 UTC, merged