Make annotations on expect declarations comply with new compiler restriction
Kotlin/kotlinx.coroutines pull request #3815
Opened 2023-07-19 11:22 UTC by merfemor

In KT-58551 we require all annotations from expect declaration to be present on actual.

This commit fixes the following violations:

1. `DefaultDelay` has `@PublishedApi` only on expect. But it is not used from public inline functions, so we can safely remove annotation.

2. expect `IgnoreJreRequirement` has `AnnotationTarget.TYPE` which is not present in actual. This is because Java target TYPE doesn't correspond to Kotlin target TYPE. Since `IgnoreJreRequirement` is internal, we can safely change targets on expect and make them equal to actual.

2023-07-19 13:22 UTC, qwwdfsad requested changes

2023-07-19 13:22 UTC, qwwdfsad commented on kotlinx-coroutines-core/common/src/CoroutineContext.common.kt
> -@PublishedApi
Please leave it on actuals as well.
It is used not for the sake of inlining but in order to access it with the help of `@Suppress` from a different KLib. `@PublishedApi` guarantees a stable unmangled name here

2023-07-21 10:41 UTC, qwwdfsad reviewed
Please merge the suggestions and it's good to go

2023-07-21 10:41 UTC, qwwdfsad commented on kotlinx-coroutines-core/common/src/CoroutineContext.common.kt
> +@PublishedApi // to have unmangled name when using from other modules
```suggestion
@PublishedApi // to have unmangled name when using from other modules via suppress
```

2023-07-21 10:41 UTC, qwwdfsad commented on kotlinx-coroutines-core/js/src/CoroutineContext.kt
> +@PublishedApi
```suggestion
@PublishedApi // Used from kotlinx-coroutines-test via suppress, not part of ABI
```

2023-07-21 10:41 UTC, qwwdfsad commented on kotlinx-coroutines-core/common/src/internal/StackTraceRecovery.common.kt
> +@PublishedApi // published for the multiplatform implementation of kotlinx-coroutines-test
```suggestion
@PublishedApi // Used from kotlinx-coroutines-test and reactor modules via suppress, not part of ABI
```

2023-07-21 11:10 UTC, mshishkina approved these changes

2023-07-21 13:24 UTC, merged