Stabilize CoroutineStart.ATOMIC
Kotlin/kotlinx.coroutines pull request #4169
Opened 2024-07-08 13:02 UTC by zuevmaxim

Fix #4151

2024-07-10 12:43 UTC, qwwdfsad approved these changes

2024-07-10 12:43 UTC, qwwdfsad commented on kotlinx-coroutines-core/common/src/CoroutineStart.kt
> +     * The coroutine stated with [ATOMIC] is guaranteed to start execution even if its [Job] was cancelled.
Probably you've meant `started` instead of `stated`?

2024-07-10 13:05 UTC, dkhalanskyjb requested changes

2024-07-10 13:05 UTC, dkhalanskyjb commented on kotlinx-coroutines-core/common/src/CoroutineStart.kt
> +     * This is a **delicate** API. The coroutine starts execution even if its [Job] is canceled before starting.
```suggestion
     * This is a **delicate** API. The coroutine starts execution even if its [Job] is cancelled before starting.
```
Both versions are correct, but we use "cancelled" throughout the codebase.

2024-07-10 13:05 UTC, dkhalanskyjb commented on kotlinx-coroutines-core/common/src/CoroutineStart.kt
> +     * is not allowed if the coroutine's scope, which is tied to the element's lifecycle, has been canceled.
```suggestion
     * is not allowed if the coroutine's scope, which is tied to the element's lifecycle, has been cancelled.
```
Ditto.

2024-07-10 13:05 UTC, dkhalanskyjb commented on kotlinx-coroutines-core/common/src/CoroutineStart.kt
> +     * For example, closing a channel used by a producer:
Is this a complete sentence? Maybe explain the idea more verbosely, like "For example, this `producer` guarantees that the channel will be eventually closed, even if the coroutine scope is cancelled before `producer` is called:"?

2024-07-10 13:05 UTC, dkhalanskyjb commented on kotlinx-coroutines-core/common/src/CoroutineStart.kt
> +     * However, the resources used in within a coroutine may rely on the cancellation mechanism,
```suggestion
     * However, the resources used within a coroutine may rely on the cancellation mechanism,
```
A typo?

2024-07-11 06:35 UTC, dkhalanskyjb approved these changes

2024-07-11 07:15 UTC, merged