Introduce Flow.any, Flow.all, Flow.none
Kotlin/kotlinx.coroutines pull request #4249
Opened 2024-10-14 21:25 UTC by CLOVIS-AI

As discussed in #4212.

This is my first proper contribution to Coroutines, so please be nice :)

At this stage, my goals are:
• Optimal API surface
• Correctness

I have not made any attempts to improve performance. In particular, I wouldn't be surprised if `any` could be improved. I believe `all` and `none` are optimal.

2024-10-14 21:27 UTC, CLOVIS-AI commented
I took inspiration from other tests, which seem to use `expect(Int)` and `finish(Int)`, but I'm not completely sure what they're for nor how to use them, so I didn't. Please let me know if they are necessary.

2024-10-15 09:00 UTC, dkhalanskyjb requested changes
`expect` and `finish` are used to describe when exactly which code is run. If there are 100 steps, the chain of calls must be `expect(1)`, `expect(2)`, `expect(3)` ... `finish(100)` and nothing else. If the test is broken and `expect(5)` runs before `expect(4)` did, the test fails.

This isn't useful for the tests you've already written. It could potentially be useful for tests that are missing, those that show short-circuiting behavior: `flow { emit(1); fail("unreached") }.any { it == 1 }` should finish without an error. Or maybe not.

2024-11-22 19:05 UTC, qwwdfsad commented
@CLOVIS-AI would you like to continue this PR or should we handle it from here?

2024-11-25 09:01 UTC, CLOVIS-AI commented
I would love to, but sadly my schedule doesn't allow me too… Feel free to make the changes you want if I'm too slow :)

2024-12-19 11:45 UTC, dkhalanskyjb commented
Closed in favor of #4304

2024-12-19 11:45 UTC, closed without merging