Rethrow AbortFlowException upon cancellation (#4034)
Kotlin/kotlinx.coroutines pull request #4254
Opened 2024-10-21 06:38 UTC by jxdabc

collectWhile catches AbortFlowException even if the CoroutineScope is cancelled while waiting on child tasks, causing it to fail to respond to cancel().

2024-10-21 10:08 UTC, dkhalanskyjb requested changes

2024-10-21 10:08 UTC, dkhalanskyjb commented on kotlinx-coroutines-core/common/src/flow/operators/Limit.kt
> +        if (!coroutineContext.isActive) { throw e }
Why not just `ensureActive()`?

2024-10-21 10:08 UTC, dkhalanskyjb commented on kotlinx-coroutines-core/common/test/flow/terminal/FirstTest.kt
> +    fun test() = runTest {
The name of the test is not informative.

2024-10-21 10:08 UTC, dkhalanskyjb commented on kotlinx-coroutines-core/common/test/flow/terminal/FirstTest.kt
> +    }
In this scenario, it's worth it to use `expect` and `finish` to assert the order of execution. The rules:
* `expect(1)` is the first invocation in any test.
* `expect(n + 1)` can only be called after `expect(n)`.
* `finish(n + 1)` can only be called after `expect(n)`.
* Each test that uses an `expect` must call `finish`.
* After `finish`, no extra `expect` or `finish` can be called.

With this, we can ensure that indeed, the test checks what we want it to check: first, cancellation happens, then, `first` throws a `CancellationException`.

2024-10-21 13:54 UTC, jxdabc commented
comments resolved

2024-11-06 18:00 UTC, dkhalanskyjb approved these changes

2024-11-07 12:00 UTC, merged

2024-11-07 12:00 UTC, dkhalanskyjb commented
Thanks!