Dispatch exception path
Kotlin/kotlinx.coroutines pull request #4272
Opened 2024-11-11 11:58 UTC by qwwdfsad

2024-11-11 12:13 UTC, qwwdfsad commented
Looking at https://github.com/Kotlin/kotlinx.coroutines/issues/4209#issuecomment-2324575057, I have yet to see an elegant, generalized solution to our problem that is neither a breaking change nor a contract breach

2025-02-17 11:28 UTC, dkhalanskyjb requested changes

2025-02-17 11:28 UTC, dkhalanskyjb commented on kotlinx-coroutines-core/common/src/intrinsics/Undispatched.kt
> +    throw throw recoverStackTrace(e.cause, uCont)
One `throw` should be enough.

2025-02-17 11:28 UTC, dkhalanskyjb commented on kotlinx-coroutines-core/common/src/intrinsics/Undispatched.kt
> +private fun ScopeCoroutine<*>.dispatchException(e: DispatchException) {
I think this function should be inlined. It's not obvious that it calls `makeCompleting`.

2025-02-17 11:28 UTC, dkhalanskyjb commented on kotlinx-coroutines-core/jvm/test/FailFastOnStartTest.kt
> +import java.util.concurrent.TimeoutException
Are these imports used?

2025-02-17 11:28 UTC, dkhalanskyjb commented on kotlinx-coroutines-core/common/src/intrinsics/Undispatched.kt
> +    makeCompleting(CompletedExceptionally(e.cause))
Why not `makeCompletingOnce`, to highlight the aspects of this codepath that are different from the happy path?

2025-02-17 11:28 UTC, dkhalanskyjb commented on kotlinx-coroutines-core/jvm/test/FailFastOnStartTest.kt
> +        // Hack to avoid waiting for test completion
Where's the hack?

2025-02-17 11:28 UTC, dkhalanskyjb commented on kotlinx-coroutines-core/jvm/test/FailFastOnStartTest.kt
> +    fun testFlowOn()  {
```suggestion
    fun testFlowOn() {
```

2025-02-18 11:08 UTC, qwwdfsad commented on kotlinx-coroutines-core/common/src/intrinsics/Undispatched.kt
> +    throw throw recoverStackTrace(e.cause, uCont)
I wanted to be extra-sure the exception is thrown

2025-02-18 11:10 UTC, qwwdfsad commented on kotlinx-coroutines-core/common/src/intrinsics/Undispatched.kt
> +private fun ScopeCoroutine<*>.dispatchException(e: DispatchException) {
I am, in general, for the opposite approach -- get rid of all "very uncommon" cases from a code path that is supposed to be followed. I renamed the function and changed return type to be `Nothing` for the readability sake

2025-02-18 11:10 UTC, qwwdfsad commented on kotlinx-coroutines-core/jvm/test/FailFastOnStartTest.kt
> +import java.util.concurrent.TimeoutException
Nope. Fixed

2025-02-18 11:13 UTC, qwwdfsad commented on kotlinx-coroutines-core/jvm/test/FailFastOnStartTest.kt
> +        // Hack to avoid waiting for test completion
Made the comment more straightforward

2025-03-10 11:37 UTC, dkhalanskyjb approved these changes

2025-03-10 11:39 UTC, merged